---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

    - name: "Node Tests"
      addons: skip
      script: npm run nodetest

    - stage: "Deploy"
      name: "Deploy"
      addons: ignore
      cache: ignore
      env: ignore
      before_install: ignore
      install: ignore
      script: ignore
      deploy:
        provider: npm
        email: kellyselden@gmail.com
        api_key:
          secure: S7FYQ8Oc2+la4dTaD/3SBz8yMC5a6LbMg5WlhYjO9LERkl87AgI4mOR/KSuERGuXsFLdYmBHn6RsK/LOMH450FJzUTxNNSskut+TbFDxYhm8DwGb1mWKgLe1SgHp/D/qpPIcX4bn5nxOywe+E4ZqKWG10jLRw1Vz1pM6n6KlGpER3q+6xaO1fg4weCemJftAG6ZaixFPQitQVTh2U5cBU7qrTxPz1WN18jS1i2sxOtKfPC5e1jSz/oqOJL+Hgd5VJgcRD/KdPLhmIz1W9O0a8P/q4UnMvsmBB1BVrV5X3+hD4E9SwGTMxB2x1d0WA1XgnEJ9Zitjrk1ugL6VQUiZ8Vhmt5sSE+ehpMfrxeK+ix/2L6I+rb+87YS3Hz3zUfThhqwkcihgNalRc+wuji4LK+VKLNPfCBnaAdjM0irW8rofXY40JVvErrIbVdrZzbFJSSzB6o689jyabFVtzu86sVWoQRzwt7xT54lrYVr9dhnAM2w+EKrXHqXj/Hdduqjn4v7VLbBu3gYP0j0NwPBeONe9kae1aSjZIM3pGiyQ2sq644+Cbcj5DorJRZ41JSsh6fLo6hPhsE6G2yAhmKKU+3iXoCx2HUIL7TsDldQfZKw3jfkoEHGwRexLV+3v/rqqJ6dKED+nTR8WVDVY3xrzKnw0sOWi2aiqM/NujDZFBQE=
        on:
          tags: true
          repo: kellyselden/ember-macro-helpers

before_install:
  - npm config set spin false
  - npm install -g npm@6
  - npm --version

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
