---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

sudo: false

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.*$/

cache:
  directories:
    - $HOME/.npm

env:
  - NPM_RUN_NODETEST=true
  # we recommend new addons test the current and previous LTS
  # as well as latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  include:
    - stage: Deploy
      cache: ignore
      env: ignore
      before_install: ignore
      install: ignore
      script: ignore
      deploy:
        provider: npm
        email: kellyselden@gmail.com
        api_key:
          secure: SrFuCVd6N+7rrWSfc/lqcaG4qJ8VTq0HhPSjhaPtFdrB7oK1YeEDDL7x9JJYj6RuUR8usT/ydo/P21UOND8/CpxXUjSTJk9pfnB3VhmTPxUUB3sTnCh5lURTH4UScjX7shNZhl2N9ClEaJqet90GDnmxXCZN7tdqZ3y03cqzLrgZEbXe94LUXbxVBOJz5xjMs4yeOAjzeg6M1hTIpMM4DQFtEpx6pWVgr16PwUFAGmzpdMYX1xRXvb1GXKT8qQaBSR1MLXY2qe+oQnYWQ3XF9pzP9HnurLzS4PEkp+s9JPjkrqUwnbvvNjQrAXjHifazZhvlcmOgH4MA/yCF9wn/IKiNlH5k7dBnh/Syw+sSlyRDrEKYF29E0xS4cDA5KBToUPQ30HezdvwLNPfY1agIQLrExSdrGN6mA50ZFDuMXztY1v6/GQCe/nbHjEmDeYxlYnkNUjpvINAWYja/iKCeKD3ZFPABGxdHF+UteSzONJ+OGZiR/bIZZ5s21Nzmlldap9mMLocSXvSivPYpZ8NZEaMGGFf6A5SWYhvqMyqnuVktyms/IN3B9kL5qJrO+7JhoaFowX6CxvA+dccoTNFE+k2JIZKYT2B4to7c7jtf+Y3SH5wMDVabpsbIiHaEuj69ROrrxBG2wa45wjXacmHPowyfC+zFSWik7lZisfBuRoA=
        on:
          tags: true
          repo: kellyselden/ember-macro-helpers

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - test "$NPM_RUN_NODETEST" != true || npm run nodetest
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - test "$NPM_RUN_NODETEST" = true || node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
